---
apiVersion: v1
kind: Service
metadata:
  name: agones-gameserver-tcp
spec:
  type: LoadBalancer
  selector:
    agones.dev/gameserver: simple-game-server
  ports:
  - protocol: TCP
    port: 9151 # local port
    targetPort: 9151
---
apiVersion: v1
kind: Service
metadata:
  name: agones-gameserver-udp
spec:
  type: LoadBalancer
  selector:
    agones.dev/gameserver: simple-game-server
  ports:
  - protocol: UDP
    port: 9150 # local port
    targetPort: 9150